# Permalinks
permalink:        pretty

# Setup
title:            Gordon lab
tagline:          'JGI'
description:      'Computational Genomics'
url:
baseurl:          /

author:
  name:           'Sean Gordon'
  url:            sgordon007.github.io

paginate:         5


github:
  repo:           https://github.com/sgordon007/sgordon007.github.io

collections:
- people
- publications
