# Permalinks
permalink:        pretty

# Setup
title:            Sean Gordon
tagline:          'JGI'
description:      'Computational Genomics'
url:              ../
baseurl:          sgordon007.github.io

author:
  name:           'Sean Gordon'
  url:            ../

paginate:         5


github:
  repo:           https://github.com/sgordon007/sgordon007.github.io

collections:
- people
- publications
